### ISSUE TITLE
Improve contrast for WCAG compliance

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/nuxt-datocms-module#7]
The yellow highlight color can be hard to read. Replace it with Voorhoede blue?

![Screenshot 2022-01-04 at 12 13 07](https://user-images.githubusercontent.com/1516059/148051014-c05f7643-980b-4f71-89ac-0c5e5d459d8d.jpg)

**Comment by Frankwarnaar** [comment]
Fixed in https://github.com/voorhoede/nuxt-datocms-module/commit/d7ece14ec191c39a653a6144a0caeab62d51797a
